name: checkout

on: [push]

jobs:
    checkout-using-actions:
      runs-on: ubuntu-latest
      steps:
        - name: before checkout
          run: |
             ls -a
        - name: action checkout
          uses: actions/checkout@v3
        - name: list all files
          run: |
            ls -a
    checkout-and-display-files:
      runs-on: ubuntu-latest
      steps:
        - name: list files before
          run: ls -a
        - name: checkout
          run: |
            git init
            git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
            git fetch origin
            git checkout main
        - name: list files after
          run: |
            ls -a