name: repository event

on:
  push:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - assigned
      - synchronize

jobs:
    checkout-events:
        runs-on : ubuntu-latest
        steps:
          - name: print out values
            run: |
              echo $GITHUB_SHA
              echo $GITHUB_REF
          - name: checkout here now
            uses: actions/checkout@v3
          - name: print all files
            run: ls -a

