name: first run

on:
  - push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run : echo "My first workflow"
      - name: Check java version installed
        run: |
          java --version
          ls

  parallel-job-runs:
    runs-on: windows-latest
    needs:
      - run-shell-commands
    steps:
      - name: print window directory
        run : pwd
      - name: pass error
        run : pwd


  dependent-job:
    runs-on: windows-latest
    steps: 
      - name: check other programming vaersion
        run: |-
          node --version
          python --version