name: Ogbu isreal

on:
  - push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run : echo "My first workflow"
      - name: Check java version installed
        run: |
          java -v
          ls