name: manual trigger

on:
    workflow_dispatch:


jobs:
    manual-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: test first manual workflow
              run: echo $GITHUB_REF