name: manual trigger

on:
    workflow_dispatch:


jobs:
    job-0:
        runs-on: ubuntu-latest
        steps:
            - name: test first manual workflow
              run: echo $GITHUB_REF
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: second test
              run: echo "I love my job as a software engineer"