name: pull-request-target

on:
  push:
    branches:
        - main
  pull_request_target:
    types:
      - closed

jobs:
    pull-request-event:
        runs-on: ubuntu-latest
        steps:
          - name: trigger comment on merging pull-request
            uses: actions/github-script@v6
            with:
              script: |
                    github.rest.issues.createComment({
                    ownner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: "Thanks for your contribution !" 
                    });
