name: pull-request-target

on:
  pull_request_target:
    types:
      - closed
      - opened

jobs:
    pull-request-event:
        runs-on: ubuntu-latest
        steps:
          - name: trigger comment on merging pull-request
            id: request-id
            uses: actions/github-script@v7
            with:
              result-encoding: string
              retries: 3
              retry-exempt-status-codes: 400,401
              script: |
                    github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: 'Thanks for your contribution' 
                    });
          - name: print result
            run: |
              echo "${{ steps.request-id.outputs }}"
